# Generated by Django 3.1.13 on 2021-12-12 02:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('blend_pct', models.CharField(max_length=50)),
                ('twists', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BranchMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('contact_person_name', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=64)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.articlemaster')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLedgerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('gst_number', models.CharField(max_length=20, unique=True)),
                ('supplier_status', models.BooleanField(default=False)),
                ('address1', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.UUIDField(unique=True)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CLOSE', 'CLOSE')], default='PENDING', max_length=9)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.branchmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.companyledgermaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLineItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_on', models.DateTimeField(default=datetime.datetime(2021, 12, 12, 7, 48, 17, 651024))),
                ('quantity', models.FloatField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METER', 'METER')], default='KG', max_length=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.colormaster')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.FloatField(default=0)),
                ('net', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METER', 'METER')], default='KG', max_length=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.companyledgermaster')),
                ('lineitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transactionlineitemdetails')),
            ],
        ),
    ]
