# Generated by Django 3.1.13 on 2021-12-12 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('METER', 'METER'), ('KG', 'KG')], default='KG', max_length=5),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='required_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 11, 25, 40, 333228)),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='unit',
            field=models.CharField(choices=[('METER', 'METER'), ('KG', 'KG')], default='KG', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='transactionlineitemdetails',
            unique_together={('transaction', 'article', 'colour')},
        ),
    ]
