# Generated by Django 3.1.13 on 2021-12-12 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20211212_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlineitemdetails',
            name='tn_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('METER', 'METER')], default='KG', max_length=5),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='required_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 12, 19, 15, 24120)),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('METER', 'METER')], default='KG', max_length=5),
        ),
    ]
