# Generated by Django 3.1.13 on 2021-12-12 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20211212_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='lineitem',
        ),
        migrations.AddField(
            model_name='transactionlineitemdetails',
            name='inventory_items',
            field=models.ManyToManyField(to='transaction.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='required_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 16, 20, 0, 769621)),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='transaction.transaction'),
        ),
    ]
