# Generated by Django 3.1.13 on 2021-12-12 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20211212_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('METER', 'METER')], default='KG', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='required_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 16, 33, 9, 898189)),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('METER', 'METER')], default='KG', max_length=5),
        ),
    ]
