# Generated by Django 3.1.13 on 2021-12-12 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20211212_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='required_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 0, 18, 38, 736385)),
        ),
    ]
