# Generated by Django 3.1.13 on 2021-12-13 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20211213_0924'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('METER', 'METER'), ('KG', 'KG')], default='KG', max_length=5),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='required_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 9, 29, 22, 175159)),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='unit',
            field=models.CharField(choices=[('METER', 'METER'), ('KG', 'KG')], default='KG', max_length=5),
        ),
    ]
