# Generated by Django 3.1.13 on 2021-12-13 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20211213_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='required_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 9, 33, 45, 172980)),
        ),
    ]
