# Generated by Django 3.1.13 on 2021-12-13 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_auto_20211213_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='num',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='required_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 9, 54, 52, 135229)),
        ),
    ]
