# Generated by Django 3.1.13 on 2021-12-13 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_auto_20211213_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('METER', 'METER'), ('KG', 'KG')], default='KG', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='required_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 10, 44, 38, 148490)),
        ),
        migrations.AlterField(
            model_name='transactionlineitemdetails',
            name='unit',
            field=models.CharField(choices=[('METER', 'METER'), ('KG', 'KG')], default='KG', max_length=5),
        ),
    ]
